version: "3.8"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile  # Utilisation du Dockerfile personnalisé
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - pyspark-network
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pyspark-network

networks:
  pyspark-network:
    driver: bridge

volumes:
  db_data:
