services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"  # Exposes Jupyter Notebook on port 8888
    volumes:
      - ./work:/home/jovyan/work  # Mounts the current directory to the notebook workspace
    networks:
      - pyspark-network

networks:
  pyspark-network:
    driver: bridge