services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root          # Change this to a secure password
      MYSQL_DATABASE: openfoodfact       # The database that will be created
      MYSQL_USER: user                   # Optional: A non-root user
      MYSQL_PASSWORD: userpassword       # Optional: Password for the non-root user
    ports:
      - "3306:3306"
    networks:
      - pyspark-network
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    tmpfs:
      - /var/lib/mysql

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile  # Utilisation du Dockerfile personnalisé
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - pyspark-network
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Le service MySQL à utiliser
      PMA_USER: user  # Utilisateur MySQL (souvent root)
      PMA_PASSWORD: userpassword  # Mot de passe root MySQL
    ports:
      - "8080:80"  # Exposer phpMyAdmin sur le port 8080
    depends_on:
      - mysql
    networks:
      - pyspark-network

networks:
  pyspark-network:
    driver: bridge

volumes:
  db_data:
