version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root          # Change this to a secure password
      MYSQL_DATABASE: openfoodfact       # The database that will be created
      MYSQL_USER: user                   # Optional: A non-root user
      MYSQL_PASSWORD: userpassword       # Optional: Password for the non-root user
    ports:
      - "3306:3306"
    networks:
      - pyspark-net
    volumes:
      - ./mysql_data:/var/lib/mysql

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile  # Utilisation du Dockerfile personnalisé
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    networks:
      - pyspark-network
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pyspark-net
    depends_on:
      - mysql

networks:
  pyspark-network:
    driver: bridge

volumes:
  db_data:
